# Generated by Django 2.2.1 on 2019-05-25 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0003_auto_20190525_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='east',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='east', to='saki.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='east_point',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='game',
            name='north',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='north', to='saki.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='north_point',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='game',
            name='south',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='south', to='saki.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='south_point',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='game',
            name='west',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='west', to='saki.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='west_point',
            field=models.IntegerField(default=25000),
        ),
        migrations.CreateModel(
            name='Kyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honba', models.IntegerField(default=0)),
                ('riichi_bou', models.IntegerField(default=0)),
                ('bakaze', models.CharField(max_length=1)),
                ('agari_type', models.CharField(max_length=10)),
                ('ryukyoku_type', models.CharField(max_length=10)),
                ('point', models.IntegerField()),
                ('agari_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agari_player', to='saki.Player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saki.Game')),
                ('houju_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houju_player', to='saki.Player')),
                ('oya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oya', to='saki.Player')),
            ],
        ),
    ]
