# Generated by Django 2.2.1 on 2019-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0004_auto_20190525_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyoku',
            name='ryukyoku_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
