# Generated by Django 2.2.1 on 2019-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0005_auto_20190525_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyoku',
            name='kyoku',
            field=models.IntegerField(default=1),
        ),
    ]
