# Generated by Django 2.2 on 2019-06-13 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0006_kyoku_kyoku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyoku',
            name='agari_player',
        ),
        migrations.RemoveField(
            model_name='kyoku',
            name='houju_player',
        ),
        migrations.RemoveField(
            model_name='kyoku',
            name='oya',
        ),
        migrations.RemoveField(
            model_name='kyoku',
            name='point',
        ),
        migrations.CreateModel(
            name='KyokuPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jikaze', models.CharField(max_length=1)),
                ('point_change', models.IntegerField(default=0)),
                ('agari', models.BooleanField(default=False)),
                ('riichi', models.BooleanField(default=False)),
                ('tenpai', models.BooleanField(default=False)),
                ('houju', models.BooleanField(default=False)),
                ('kyoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saki.Kyoku')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saki.Player')),
            ],
        ),
    ]
