# Generated by Django 2.2 on 2019-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0007_auto_20190613_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyoku',
            name='bakaze',
        ),
        migrations.AddField(
            model_name='kyokuplayer',
            name='chonbo',
            field=models.BooleanField(default=False),
        ),
    ]
