# Generated by Django 2.2 on 2019-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0008_auto_20190619_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='tonpu', max_length=10),
            preserve_default=False,
        ),
    ]
