# Generated by Django 2.2 on 2019-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0009_game_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='point',
        ),
    ]
